name: prozone_app
description: Service provider management application


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.1
  get_it: ^5.0.4
  flutter_dotenv: ^3.1.0
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  equatable: ^1.2.5
  flushbar: ^1.10.4
  shared_preferences: ^0.5.12+4
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  connectivity: ^2.0.2
  provider: ^4.3.2+2
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  flutter_native_splash: ^0.2.6

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - .env

flutter_native_splash:
  image: assets/images/icon_image.png
  color: "FFFFFF"
